version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/pos.db:/app/pos.db
  frontend:
    working_dir: /app
    image: node:18-alpine
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5174:5173"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8001
